### ISSUE TITLE
ServiceCircularReferenceException when SEV and FroshProfiler is installed and active

### ISSUE THREAD

**Issue by nlubisch** [shopware-blog/shopware-environment-variables#12]
As described in the title following exception occurs if both plugins are installed and active.

> Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ServiceCircularReferenceException: Circular reference detected for service "shopware_environment_variables.source.helper.shop_provider", path: "front -> router -> shopware.routing.matchers.rewrite_matcher -> query_alias_mapper -> config -> config_factory -> shopware_environment_variables.source.helper.shop_provider -> frosh_profiler.subscriber.var_dump_collector_subscriber -> frosh_profiler.config -> shopware.plugin.cached_config_reader -> shopware.plugin.config_reader". in /var/www/shopware/vendor/symfony/dependency-injection/Container.php on line 297

**Comment by teiling88** [comment]
It seems that this service declaration https://github.com/FriendsOfShopware/FroshProfiler/blob/master/Resources/services.xml#L96 prevents decoration of the config reader from Shopware. So please contact the FroshProfiler developer instead :-)

**Comment by shyim** [comment]
Why should the usage of a service break that :stuck_out_tongue:

**Comment by brxbrx** [comment]
Are there any news about this issue?

**Comment by teiling88** [comment]
As far as I know - the Frosh Profiler Plugin has already some hacks caused of combinations of plugins. 

I have no idea how to fix it in this plugin because it is a normal service decorater - nothing more.

So I will not investigate more time in this issue but for information purpose this issue will be left opened.
